#!/bin/sh

case "$1" in
	"start")
		nvram set apps_state_autorun=4
		logger -t "$(basename "$0")" "Executing command in \"script_usbmount\"..."
		eval "$(nvram get script_usbmount)"
	;;
	"stop")
		logger -t "$(basename "$0")" "Executing command in \"script_usbumount\"..."
		eval "$(nvram get script_usbumount)"
	;;
esac
