#!/bin/sh
# $1 = event, $2 = target

[ -f "/usr/sbin/helper.sh" ] && { logger -s -t "$SCRIPT_NAME" "This service-event script is not compatible with Merlin firmware!"; exit 1; }

case "$2" in
    "firewall"|"vpnc_dev_policy"|"pms_device"|"ftpd"|"ftpd_force"|"aupnpc"|"chilli"|"CP"|"radiusd"|"webdav"|"enable_webdav"|"time"|"snmpd"|"vpnd"|"pptpd"|"openvpnd"|"yadns"|"dnsfilter"|"tr"|"tor")
        [ ! -f "/jffs/scripts/vpn-kill-switch.sh" ] && [ ! -f "/jffs/scripts/force-dns.sh" ] && [ ! -f "/jffs/scripts/tailscale.sh" ] && exit

        _TIMER=0; while { # wait till our chains disappear
            iptables -n -L "VPN_KILLSWITCH" >/dev/null 2>&1 ||
            iptables -t nat -n -L "FORCEDNS" >/dev/null 2>&1 ||
            iptables -n -L "FORCEDNS_DOT" >/dev/null 2>&1 ||
            iptables -n -L "TAILSCALE" >/dev/null 2>&1; 
        } && [ "$_TIMER" -lt "60" ]; do
            _TIMER=$((_TIMER+1))
            sleep 1
        done

        /jffs/scripts/vpn-kill-switch.sh run &
        /jffs/scripts/force-dns.sh run &
        /jffs/scripts/tailscale.sh firewall &
        
        exit
    ;;
    "allnet"|"net_and_phy"|"net"|"multipath"|"subnet"|"wan"|"wan_if"|"dslwan_if"|"dslwan_qis"|"dsl_wireless"|"wan_line"|"wan6"|"wan_connect"|"wan_disconnect"|"isp_meter")
        [ ! -f "/jffs/scripts/usb-network.sh" ] && [ ! -f "/jffs/scripts/dynamic-dns.sh" ] && exit

        _TIMER=0; while [ "$(nvram get wan0_state_t)" = "2" ] && [ "$_TIMER" -lt "15" ]; do _TIMER=$((_TIMER+1)); sleep 1; done # wait until wan goes down
        _TIMER=0; while [ "$(nvram get wan0_state_t)" != "2" ] && [ "$_TIMER" -lt "60" ]; do _TIMER=$((_TIMER+1)); sleep 1; done # wait until wan goes up

        [ -f "/jffs/scripts/usb-network.sh" ] && /jffs/scripts/usb-network.sh run &
        [ -f "/jffs/scripts/dynamic-dns.sh" ] && /jffs/scripts/dynamic-dns.sh run &

        # most of these also restart firewall so execute that too just in case
        sh "$(readlink -f "$0")" "restart" "firewall"
        
        exit
    ;;
esac

# these do not follow the naming scheme ("ACTION_SERVICE")
case "${1}_${2}" in
    "ipsec_set"|"ipsec_start"|"ipsec_restart")
        sh "$(readlink -f "$0")" "restart" "firewall"
        exit
    ;;
esac
