#!/bin/sh
# Made by Jack'lul <jacklul.github.io>
#
# /opt/usr/sbin/restore-permissions
#
# This script restores permissions and ownership of files and directories
# from the file created by save-permissions script.
#

[ -x /opt/bin/id ] || { echo "Install 'coreutils-id' package!" >&2; exit 1; }
[ "$(id -u)" -ne 0 ] && { echo "This script must run as root."; exit 1; }
[ -x /opt/bin/stat ] || { echo "Install 'coreutils-stat' package!" >&2; exit 1; }

[ -z "$1" ] && { echo "Input file not provided" >&2; exit 1; }
[ ! -f "$1" ] && { echo "Input file does not exist: $1" >&2; exit 1; }

set -e

while IFS=" " read -r perms user group path; do
    if [ -e "$path" ]; then
        echo "chown $user:$group $path"
        chown "$user:$group" "$path"
        echo "chmod $perms $path"
        chmod "$perms" "$path"
    else
        echo "Path does not exist: $path"
    fi
done < "$1"

echo "Permissions have been restored"
