#!/bin/sh
# Made by Jack'lul <jacklul.github.io>
#
# /opt/usr/sbin/samba_multicall
#
# This script is to replace /usr/sbin/samba_multicall so that Entware's Samba
# is used instead of the firmware's one
#
# You will also need to have /opt/etc/init.d/S90replace-samba script to mount this
#
# Samba 4 config docs: https://www.samba.org/samba/docs/4.18/man-html/smb.conf.5.html
#
# Based on:
#  https://www.snbforums.com/threads/how-to-get-samba-4-18-8-running-on-an-rt-ax86u-pro-running-merlin-3006-102-4_0.94825/#post-957792
#

#shellcheck disable=SC2086

# Path to custom-configs script from https://github.com/jacklul/asuswrt-scripts
custom_configs=/jffs/scripts/jas/custom-configs.sh

#########################

# Modify config for Samba 4 compatibility if not already done
# Check for '--version' is added just to let us use 'smbd --version' in the postconf script
if ! grep -Fq "Modified by samba_multicall" /etc/smb.conf && ! echo "$*" | grep -q "\-\-version"; then
    fd=1000
    lockfile=/var/lock/samba_multicall.lock
    eval exec "$fd>$lockfile"

    timeout=15
    while ! flock -nx "$fd" && [ "$timeout" -ge 0 ]; do
        timeout=$((timeout-1))
        sleep 1
    done
    [ "$timeout" -le 0 ] && exit 1

    # Manually call custom-configs script if it exists
    if [ "$(uname -o)" != "ASUSWRT-Merlin" ] && [ -x "$custom_configs" ] && ! grep -Fq "Modified by" /etc/smb.conf; then
        "$custom_configs" modify /etc/smb.conf
    fi

    # Remove options not supported by Samba 4
    sed '/^display charset/d' -i /etc/smb.conf
    sed '/^use spnego/d' -i /etc/smb.conf
    sed '/^auth methods/d' -i /etc/smb.conf

    # Logging is not enabled by default in Samba 4
    sed "/^log file/a logging = file" -i /etc/smb.conf

    # Do not limit max protocol to SMB2
    sed '/^max protocol = SMB2/d' -i /etc/smb.conf

    # Set private directory to /etc/samba
    if ! grep -q "^private dir = /etc/samba" /etc/smb.conf; then
        sed '/^private dir =/ s/^/#/' -i /etc/smb.conf
        sed "/^\[global\]/a private dir = /etc/samba" -i /etc/smb.conf
    fi

    # Set smbpasswd file to /etc/samba/smbpasswd if using smbpasswd backend
    if grep -q "^passdb backend = smbpasswd" /etc/smb.conf; then
        sed "/^passdb backend = smbpasswd/a smb passwd file = /etc/samba/smbpasswd" -i /etc/smb.conf
    fi

    # Set pid directory to /var/run/samba
    if ! grep -q "^pid directory = /var/run/samba" /etc/smb.conf; then
        sed '/^pid directory =/ s/^/#/' -i /etc/smb.conf
        sed "/^\[global\]/a pid directory = /var/run/samba" -i /etc/smb.conf
    fi

    echo "# Modified by samba_multicall" >> /etc/smb.conf
    flock -u "$fd"
    rm -f "$lockfile"
fi

case "$(basename "$0")" in
    smbd)
        exec /opt/sbin/smbd "$@"
    ;;
    nmbd)
        exec /opt/sbin/nmbd "$@"
    ;;
    smbpasswd)
        [ -x /opt/var/run/smbpasswd ] && exec /opt/var/run/smbpasswd "$@"
        exec /opt/sbin/smbpasswd "$@"
    ;;
esac
