#!/bin/sh
# /opt/etc/init.d/S00overrides
# This script allows you to override the default startup scripts in /opt/etc/init.d
# by creating a script with the name prefixed with "override-" in the same directory.

#shellcheck disable=SC2044
case $1 in
    start|restart|reconfigure)
        for i in $(find /opt/etc/init.d/ -name 'S*' -o -name 'rc.*'); do
            if [ -f "$i" ]; then
                b="$(basename "$i")"

                if [ -x "/opt/etc/init.d/override-$b" ] && [ ! -L "$i" ]; then
                    mv -f "$i" "$i.old"
                    chmod -x "$i.old"
                    ln -s "/opt/etc/init.d/override-$b" "$i"
                fi
            fi
        done
    ;;
    stop|kill)
        for i in $(find /opt/etc/init.d/ -name 'S*' -o -name 'rc.*'); do
            if [ -L "$i" ] && [ -f "$i.old" ]; then
                rm -f "$i"
                mv -f "$i.old" "$i"
                chmod +x "$i"
            fi
        done
    ;;
    check)
        for i in $(find /opt/etc/init.d/ -name 'S*' -o -name 'rc.*'); do
            if [ -f "$i" ]; then
                b="$(basename "$i")"

                if [ -x "/opt/etc/init.d/override-$b" ] && [ ! -L "$i" ]; then
                    echo "dead"
                    exit 1
                fi
            fi
        done

        echo "alive"
    ;;
esac

# Please note that if you update or install packages through opkg then their initd script will be overwritten
# You will have to run /opt/etc/init.d/S00overrides restart to reapply the changes
