#!/bin/sh
# Made by Jack'lul <jacklul.github.io>
#
# /opt/etc/init.d/S90replace-samba
#
# This script mounts /opt/usr/sbin/samba_multicall to /usr/sbin/samba_multicall
#

[ ! -x /opt/usr/sbin/samba_multicall ] && exit 0
{ [ ! -x /opt/sbin/smbd ] || [ ! -x /opt/sbin/nmbd ] ; } && exit 0

mkdir -p /opt/var/log/samba
mkdir -p /opt/var/lib/samba/private
mkdir -p /opt/var/cache/samba
mkdir -p /opt/var/run/samba/ncalrpc

case $1 in
    start|restart)
        chmod -x /opt/etc/init.d/S91smb # Disable Entware's smb init script

        if ! mount | grep -Fq "on /usr/sbin/samba_multicall "; then
            cp /usr/sbin/smbpasswd /opt/var/run/smbpasswd
            mount -o bind /opt/usr/sbin/samba_multicall /usr/sbin/samba_multicall
            service restart_samba
        fi
    ;;
    stop|kill)
        if mount | grep -Fq "on /usr/sbin/samba_multicall "; then
            umount /usr/sbin/samba_multicall
            service restart_samba
        fi

        rm -f /opt/var/run/smbpasswd
    ;;
    check)
        if ! mount | grep -Fq "on /usr/sbin/samba_multicall "; then
            echo "dead"
            exit 1
        fi

        echo "alive"
    ;;
esac
