#!/bin/sh
# Made by Jack'lul <jacklul.github.io>
#
# /opt/etc/init.d/S90replace-samba
#
# This script mounts /opt/usr/sbin/samba_multicall as /usr/sbin/samba_multicall
# and prevents service startup through S91smb init script
#

[ ! -x /opt/usr/sbin/samba_multicall ] && exit 0
{ [ ! -x /opt/sbin/smbd ] || [ ! -x /opt/sbin/nmbd ] ; } && exit 0

# Directories required by Entware's Samba (taken from S91smb)
mkdir -p /opt/var/log/samba
mkdir -p /opt/var/lib/samba/private
mkdir -p /opt/var/cache/samba
mkdir -p /opt/var/run/samba/ncalrpc

case $1 in
    start|restart)
        chmod -x /opt/etc/init.d/S91smb # Disable Entware's smb init script

        if ! mount | grep -Fq "on /usr/sbin/samba_multicall "; then
            # Copy firmware's samba_multicall as without it firmware won't be able to manage users (smbpasswd)
            if [ ! -f /opt/var/lib/firmware-samba/samba_multicall ] || [ "$(md5sum /opt/var/lib/firmware-samba/samba_multicall | awk '{print $1}')" != "$(md5sum /usr/sbin/samba_multicall | awk '{print $1}')" ]; then
                mkdir -p /opt/var/lib/firmware-samba
                cp -f /usr/sbin/samba_multicall /opt/var/lib/firmware-samba/samba_multicall
                chmod +x /opt/var/lib/firmware-samba/samba_multicall
                ln -s /opt/var/lib/firmware-samba/samba_multicall /opt/var/lib/firmware-samba/smbpasswd
            fi

            mount -o bind /opt/usr/sbin/samba_multicall /usr/sbin/samba_multicall
            service restart_samba # immediately restart through firmware service command
        fi
    ;;
    stop|kill)
        if mount | grep -Fq "on /usr/sbin/samba_multicall "; then
            umount /usr/sbin/samba_multicall
            service restart_samba
        fi
    ;;
    check)
        if ! mount | grep -Fq "on /usr/sbin/samba_multicall "; then
            echo "dead"
            exit 1
        fi

        echo "alive"
    ;;
esac
